name: CI

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          configuration: phpunit.xml.dist
          version: 7
          php_version: 7.2
